/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "name.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
marksprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name nameproc_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NAMEPROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nameproc_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l1n1proc_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L1N1PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_name;
		local = (char *(*)(char *, struct svc_req *)) l1n1proc_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l1n2proc_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L1N2PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) l1n2proc_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l2n1proc_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L2N1PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) l2n1proc_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_5(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l2n2proc_5_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L2N2PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) l2n2proc_5_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_6(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l2n3proc_6_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L2N3PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) l2n3proc_6_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
marksprog_7(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		name l2n4proc_7_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case L2N4PROC:
		_xdr_argument = (xdrproc_t) xdr_name;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) l2n4proc_7_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MARKSPROG, MARKSVERS);
	pmap_unset (MARKSPROG, L1N1VERS);
	pmap_unset (MARKSPROG, L1N2VERS);
	pmap_unset (MARKSPROG, L2N1VERS);
	pmap_unset (MARKSPROG, L2N2VERS);
	pmap_unset (MARKSPROG, L2N3VERS);
	pmap_unset (MARKSPROG, L2N4VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, MARKSVERS, marksprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, MARKSVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L1N1VERS, marksprog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L1N1VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L1N2VERS, marksprog_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L1N2VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N1VERS, marksprog_4, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N1VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N2VERS, marksprog_5, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N2VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N3VERS, marksprog_6, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N3VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N4VERS, marksprog_7, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N4VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, MARKSVERS, marksprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, MARKSVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L1N1VERS, marksprog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L1N1VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L1N2VERS, marksprog_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L1N2VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N1VERS, marksprog_4, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N1VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N2VERS, marksprog_5, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N2VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N3VERS, marksprog_6, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N3VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MARKSPROG, L2N4VERS, marksprog_7, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MARKSPROG, L2N4VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
